In [1]:
# Imports
import torch

In [2]:
# Let's create a new tensor and use requires_grad=True

a = torch.rand(10, requires_grad=True)
a

tensor([0.7144, 0.7951, 0.9549, 0.1301, 0.7697, 0.0374, 0.5365, 0.1826, 0.4337,
        0.2327], requires_grad=True)

In [3]:
# Let's build up a computation graph
# notice how this tensor had a special function called grad_fn

b = a * 2
b

tensor([1.4289, 1.5901, 1.9098, 0.2602, 1.5393, 0.0748, 1.0730, 0.3653, 0.8673,
        0.4654], grad_fn=<MulBackward0>)

In [4]:
# Lets compute one more tensor
c = b.mean()
c

tensor(0.9574, grad_fn=<MeanBackward0>)

In [5]:
# Since this is a scalar we can call backward on it
c.backward()

In [6]:
# Now we can see the gradients of a
a.grad

tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000,
        0.2000])

In [7]:

torch.cuda.memory_allocated()

0

In [8]:

a = torch.rand(2**20, requires_grad=True, device="cuda")
torch.cuda.memory_allocated() / 1024.0**2

AssertionError: Torch not compiled with CUDA enabled

In [9]:
b = torch.relu(a)
torch.cuda.memory_allocated() / 1024.0**2

0.0

In [10]:

b = a
for _ in range(100):
    b = torch.relu(b)
torch.cuda.memory_allocated() / 1024.0**2

0.0

In [11]:

b.sum().backward()
torch.cuda.memory_allocated() / 1024.0**2

0.0

In [12]:
a.grad

tensor([1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000, 1.2000,
        1.2000])